# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c88d5d41719eca2aaf9feb26a2a0a5d394a57ce6ad9de05938a08081781ee73d2c7daffc6dcfa066c97d5b9b51e9de23620534bbed97135c3d13ed2cac7e33cd

test:
  secret_key_base: 6adc3fc24b97722032c47e2bcbdd5426226da4330d662c8d594bfbb945616077e4b806cd4c6d06d143f08b7a4081b67bfc12f78def4d17cbeff938e716a39819

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
