# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eda47c33e7a75e9f871145cbf70f6bb67c4780d1764c2c086003d1a5e895baecbbe4671e19eda663fa8915b1b344fc4113b0553852a5176c35e29952520e85c8

test:
  secret_key_base: e755697db3420742f11662bf4d9a14263ff53a1d3071e48665aa16cb3f99be303c68020fa279172a55d3ba68a5828ee0e4a3e3b25367e124c98e984c636f5f36

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
